In [2]:
import numpy as np

In [3]:
lst = list(range(1,30))
arr1 = np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
arr2 = np.arange(1,30)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,12,3,4,4,3])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12,  3,  4,  4,  3])

In [6]:
arr4 = np.zeros((10))
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr5 = np.ones((10))
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr6 = np.zeros((5,10))
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr7 = np.linspace(1,10,20)
arr7

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [10]:
arr= np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
arr8 = np.arange(0,30).reshape(10,3)
arr8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

## random numbers array gen

In [12]:
arr_1d = np.random.randint(1,5,9)
arr_1d

array([3, 4, 1, 4, 3, 2, 4, 1, 2])

In [13]:
arr_2d = np.random.randint(1,5,(5,2))
arr_2d

array([[4, 2],
       [2, 4],
       [1, 1],
       [4, 2],
       [4, 2]])

In [14]:
arr_3d = np.random.random(10)
arr_3d


array([0.53890377, 0.73205499, 0.81449764, 0.89692789, 0.24443202,
       0.94068659, 0.37140527, 0.07345714, 0.38832591, 0.32463195])

In [15]:
arr_4D = np.random.random((5,10))
arr_4D

array([[0.33314284, 0.12210321, 0.01054244, 0.96576059, 0.29863803,
        0.29529845, 0.9864953 , 0.12006493, 0.43196753, 0.33499593],
       [0.21874264, 0.62261707, 0.02482432, 0.96696757, 0.69660152,
        0.94327303, 0.33827447, 0.36418723, 0.77772993, 0.04160748],
       [0.77734741, 0.33565758, 0.72164139, 0.98779005, 0.72903052,
        0.54333296, 0.24269915, 0.56627689, 0.34442287, 0.74678582],
       [0.79584416, 0.9478588 , 0.44084715, 0.01321056, 0.31214276,
        0.59871558, 0.45280868, 0.94240382, 0.86433674, 0.01142348],
       [0.61939642, 0.60375842, 0.33926277, 0.08710259, 0.4126235 ,
        0.56764548, 0.99970129, 0.5015917 , 0.2920813 , 0.50485504]])

### Array Attributes

In [16]:
arr = np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [17]:
arr.shape

(12, 5)

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr.ndim

2

In [20]:
arr.size

60

In [21]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [22]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [24]:
list_2d = [[1,2,3],[4,5,6]]
list_2d

[[1, 2, 3], [4, 5, 6]]

In [25]:
arr = np.array(list_2d)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr.shape

(2, 3)

In [27]:
arr.T.shape

(3, 2)

### Accessing elements from 1D and 2D array

for 1d array
[row_start:end:step/skip]

for 2d array
[row-start:end:skip/step,column_start:end:skip/step]

In [28]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [29]:
arr[15]

15

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
## 2d array
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
arr[1]

array([5, 6, 7, 8, 9])

In [34]:
arr[1,1]

6

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [36]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [38]:
arr[1,3:5]

array([8, 9])

In [39]:
arr[7:8,4][0] = 100

In [40]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [41]:
arr[11][-1]

59

In [42]:
arr[-1][-1]

59

In [43]:
arr[-1,-1]

59

In [44]:
arr[11:,-1][0]

59

In [45]:
arr[11,4]

59

### for 3d array

In [46]:
arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [47]:
arr.shape
#5 --> table
#15 -->row
#3 --> columns
###[table,row,col]     --> for 3d array

(5, 15, 3)

In [48]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [49]:
np.min(arr)

0

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [51]:
arr[0][2:]

array([2, 3, 4])

In [53]:
arr[:,0,:]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [54]:
arr[:,0:1,0:1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [55]:
arr[2]

array([10, 11, 12, 13, 14])

In [56]:
arr[2][3][1] = 100

TypeError: 'numpy.int32' object does not support item assignment

In [57]:
arr[0]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0][::-1]

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [ ]:
arr[0][::-1,::-1]

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

### Sorting in Array

In [58]:
arr1 = np.array([2,4,45,7,2,4,3])
arr2 = np.array([0,5,6,3,1],[3,2,5,3,2])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [59]:
print("hello ")

hello 
